dns-port: 53
mq-server-ip: ip
mq-server-port: 15672
mq-server-username: root
mq-server-password: password
mq-server-admin-init-queue: admin-queue
mq-server-authoritative-init-queue: authoritative-queue-ns2
mq-server-authoritative-update-exchange: authoritative-update
mq-server-authoritative-statistics-queue: statistics-queue
